server:
  port: 8082

spring:
  application:
    name: microservice-1
  security:
    oauth2:
#      client:
#        provider:
#          keycloak:
#            issuer-uri: http://auth.security-server.infra.ubu/auth/realms/security-spring
      resourceserver:
        jwt:
          issuer-uri:  http://auth.security-server.infra.ubu/auth/realms/security-spring
          jwk-set-uri: http://auth.security-server.infra.ubu/auth/realms/security-spring/protocol/openid-connect/certs